### ISSUE TITLE
有关conver2mp3文件

### ISSUE THREAD

**Issue by signupbook** [innnky/audio-preprocessing-scripts#1]
请问为什么在运行这个文件后有时候会莫名其妙地把我dataset\speaker里的文件删除，然后告诉我“No such file or directory"?
dataset的文件排布也依照structure里的编排过了

**Comment by innnky** [comment]
如果误删了您的音频数据我确实很抱歉，目前这个仓库不是很完善，而且我readme写的也不完善，依赖之类的都没有写，你说的情况可能是没有安装ffmpeg，另一方面我也只在mac和linux下经过了测试，没有在windows下通过测试，我立刻修改readme
